### ISSUE TITLE
如果可以做成web应用就好了，有没有什么思路交流一下呗

### ISSUE THREAD

**Issue by qqwqtzd** [Tenderness-5787/ZJU-Clock-In#5]
如果可以做成web应用就好了，有没有什么思路交流一下呗

**Comment by Tenderness-5787** [comment]
WEB一定会需要用户把zju通行证的账户密码上传到我的私人服务器上，我就能看到用户的账户密码了，这样没办法保证用户的账户密码安全性。 相比上传到我的服务器，还是直接用github action比较安全。

**Comment by Tenderness-5787** [comment]
> 如果可以做成web应用就好了，有没有什么思路交流一下呗
WEB一定会需要用户把zju通行证的账户密码上传到我的私人服务器上，我就能看到用户的账户密码了，这样没办法保证用户的账户密码安全性。 相比上传到我的服务器，还是直接用github action比较安全。

**Comment by Tenderness-5787** [comment]
> 如果可以做成web应用就好了，有没有什么思路交流一下呗

WEB一定会需要用户把zju通行证的账户密码上传到我的私人服务器上，我就能看到用户的账户密码了，这样没办法保证用户的账户密码安全性。 相比上传到我的服务器，还是直接用github action比较安全。

**Comment by BaldFish-Tong** [comment]
本地运行的话会出问题，显示链接过多，用.keep_alive = False也无法解决请问有什么思路吗

**Comment by Tenderness-5787** [comment]
> 本地运行的话会出问题，显示链接过多，用.keep_alive = False也无法解决请问有什么思路吗

暂时没复现你遇到的问题，我本地是正常的
