### ISSUE TITLE
关于这两天打卡失效的问题

### ISSUE THREAD

**Issue by BaldFish-Tong** [Tenderness-5787/ZJU-Clock-In#6]
近两天打卡脚本失效，提示请输入位置或者获取位置信息

**Comment by Dreamerryao** [comment]
脚本挂了- - 看起来定位那里改掉了

**Comment by cruse123** [comment]
原网站的提交表单添加了两个新的字段，分别是`"23676..."`和`"f6f25..."`，否则出现`{"e":1,"m":"请获取定位信息或者选取填写所在位置","d":{}}`错误。两个字段的信息都可以从网页中直接parse到，详见#8 。

**Comment by Tenderness-5787** [comment]
修了 先观察一下

**Comment by cruse123** [comment]
很抱歉提交了未经严格测试的代码，打卡机仍未能正常工作。
经观察，最新的打卡网页中，POST表单的两个magic字段，key和value都会变化：value是每次刷新都会变，key暂时看是一天变一次，估计与时间有关。
稍微改变regex的写法，从[原网页](https://healthreport.zju.edu.cn/ncov/wap/default/index)中同时提取key和value，暂时将key固定为32 chars，其实用`+`也可以。已有少量成功案例，请进行评估和更多的测试，谢谢！

Quick Fix:
```diff
111,112c111,113
<         new_info['23676ad88cb0953fa0e229b32e886f62'] = re.findall(r'"23676ad88cb0953fa0e229b32e886f62":\s*"([^\"]+)",', html)[0]
<         new_info['f6f259ba6791b79b64e0559fbe41050d'] = re.findall(r'"f6f259ba6791b79b64e0559fbe41050d":\s*"([^\"]+)",', html)[0]
---
>         magics = re.findall(r'"([0-9a-f]{32})":\s*"([^\"]+)"', html)
>         for item in magics:
>             new_info[item[0]] = item[1]
```

**Comment by Dreamerryao** [comment]
第一个value是原create_time字段，unix秒数
给到的是一个单向hash- - 
新的regex可以满足目前需求，reopen & PR again!

**Comment by Tenderness-5787** [comment]
感谢几位同学的帮助 打卡脚本已经恢复正常
